apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo
spec:
  selector:
    matchLabels:
      app: argocd-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd-demo
    spec:
      containers:
        - name: argocd-demo
          image: nginx
          ports:
            - containerPort: 80

